### ISSUE TITLE
Lines in documents can have multiple word elements

### ISSUE THREAD

**Issue by Raffinate** [Amaimersion/google-docs-utils#4]
If text in the line has multiple fonts or various formatting, the line is split in multiple word elements.

In that case GoogleDocsUtils.getWordElements() will find only first word node in the line and other word nodes won't be found.

This breaks all functions that are related to word nodes, such as getCaret() e.t.c.

Steps to reproduce:

1. Create text document in google docs
2. Write several lines of text
3. Format middle word in any line with different font
4. Place caret in that word
5. Execute GoogleDocsUtils.getCaret()

Expected properly initialized caret, but instead we have all fields as null

**Comment by Raffinate** [comment]
Created pull request with fix

**Comment by srgykuz** [comment]
Solved in 2.2.0 version.
